<div align="center">

# ğŸŸ¡ FIX ğŸŸ¡

</div>

## 1

ğŸŸ¢ Verificar as duas chamadas assÃ­ncronas, que estÃ£o sendo realizadas `return this.httpClient.get<Course[]>` em **Courses.Service.ts**

-> Para realizar a correÃ§Ã£o a soluÃ§Ã£o foi ao invÃ©s de usar o operadot `cathError`, usar o `tap`.
substituindo

    `this.courses$ = this.coursesServices.list().pipe(
      catchError((error) => {
        this.onError("Erro ao carregar ");
        return of([]);
      })
    );

por

    this.courses$ = this.coursesServices.list().pipe(
     tap({
       error: (error) => {
         this.onError("Erro ao carregar");
       },
     })
    );

___



## 
---
